### ISSUE TITLE
MountVolume.SetUp failed for volume "auth-proxy-certs" : secrets "auth-proxy-certs" not found

### ISSUE THREAD

**Issue by JinsYin** [matt-deboer/kuill#83]
```bash
$ kubectl apply -f kuill-example-deployment.yml

$ kubectl -n kube-system describe pod kuill-5b7bd6c875-lsbqc
Name:           kuill-5b7bd6c875-lsbqc
Namespace:      kube-system
Node:           kube-node-120/192.168.10.120
Start Time:     Thu, 01 Feb 2018 16:58:51 +0800
Labels:         name=kuill
                pod-template-hash=1636827431
                service=kuill
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kuill-5b7bd6c875","uid":"1f8a4bac-072e-11e8-bb18-d4bed9ee30d...
Status:         Pending
IP:             
Created By:     ReplicaSet/kuill-5b7bd6c875
Controlled By:  ReplicaSet/kuill-5b7bd6c875
Containers:
  kuill:
    Container ID:   
    Image:          mattdeboer/kuill
    Image ID:       
    Port:           8443/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      KUILL_PORT:         8443
      KUILL_SERVER_CERT:  /certs/auth-proxy.pem
      KUILL_SERVER_KEY:   /certs/auth-proxy-key.pem
    Mounts:
      /certs from auth-proxy-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-x9pm6 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  auth-proxy-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  auth-proxy-certs
    Optional:    false
  default-token-x9pm6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-x9pm6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                From                    Message
  ----     ------       ----               ----                    -------
  Warning  FailedMount  12m (x82 over 2h)  kubelet, kube-node-120  MountVolume.SetUp failed for volume "auth-proxy-certs" : secrets "auth-proxy-certs" not found
  Warning  FailedMount  6m (x69 over 2h)   kubelet, kube-node-120  Unable to mount volumes for pod "kuill-5b7bd6c875-lsbqc_kube-system(1f8c8ef4-072e-11e8-bb18-d4bed9ee30df)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"kuill-5b7bd6c875-lsbqc". list of unattached/unmounted volumes=[auth-proxy-certs]
  Warning  FailedSync   2m (x71 over 2h)   kubelet, kube-node-120  Error syncing pod
```

**Comment by matt-deboer** [comment]
@JinsYin sorry about that; the manifest has been updated for this now; feel free to give it a try with the latest...

**Comment by JinsYin** [comment]
It still can not work.

```bash
$ kubectl -n kube-system describe pod <pod-name>
Events:
  Type     Reason                 Age              From                   Message
  ----     ------                 ----             ----                   -------
  Normal   Scheduled              4m               default-scheduler      Successfully assigned kuill-5bbccd6675-ngv8k to kube-node-50
  Normal   SuccessfulMountVolume  4m               kubelet, kube-node-50  MountVolume.SetUp succeeded for volume "kuill-token-849h5"
  Warning  BackOff                4m (x4 over 4m)  kubelet, kube-node-50  Back-off restarting failed container
  Warning  FailedSync             4m (x4 over 4m)  kubelet, kube-node-50  Error syncing pod
  Normal   Pulling                3m (x4 over 4m)  kubelet, kube-node-50  pulling image "mattdeboer/kuill"
  Normal   Pulled                 3m (x4 over 4m)  kubelet, kube-node-50  Successfully pulled image "mattdeboer/kuill"
  Normal   Created                3m (x4 over 4m)  kubelet, kube-node-50  Created container
  Normal   Started                3m (x4 over 4m)  kubelet, kube-node-50  Started container
```

```bash
$ kubectl -n kube-system logs -f <pod-name>
time="2018-02-06T01:13:28Z" level=warning msg="OpenID+Connect authenticator is not enabled; the following required flags were missing: public-url, oidc-provider, oidc-client-id, oidc-provider-name, oidc-client-secret"
time="2018-02-06T01:13:28Z" level=warning msg="SAML authenticator is not enabled; the following required flags were missing: saml-groups-attribute, saml-sp-cert, saml-sp-key, public-url"
time="2018-02-06T01:13:28Z" level=info msg="Enabled authenticator: anonymous:anonymous => /auth/anonymous/anonymous"
time="2018-02-06T01:13:28Z" level=info msg="Enabled kubernetes api proxy for https://172.254.0.1:443"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf173f4]

goroutine 1 [running]:
github.com/matt-deboer/kuill/pkg/metrics.convertSummary(0xc4200a0280, 0x0, 0x0, 0x0, 0x0, 0xc42013ac70, 0xe, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/metrics/metrics.go:194 +0x94
github.com/matt-deboer/kuill/pkg/metrics.(*Provider).summarize(0xc420354990, 0xc420354990)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/metrics/metrics.go:97 +0x837
github.com/matt-deboer/kuill/pkg/metrics.NewMetricsProvider(0xc4203c0500, 0xf, 0xc420380dc8, 0xf58908)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/metrics/metrics.go:38 +0x9f
main.setupMetrics(0xc420446b00, 0xc420091f80, 0xc4203c0500)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:503 +0x2f
main.main.func1(0xc420446b00)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:270 +0x2cf
github.com/matt-deboer/kuill/vendor/github.com/urfave/cli.HandleAction(0x1001d00, 0x120fa50, 0xc420446b00, 0xc4201dbf20, 0x0)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/vendor/github.com/urfave/cli/app.go:503 +0x7c
github.com/matt-deboer/kuill/vendor/github.com/urfave/cli.(*App).Run(0xc420152a80, 0xc42000e1d0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/matt-deboer/kuill/vendor/github.com/urfave/cli/app.go:268 +0x6ca
main.main()
	/home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:292 +0x25ea
```

**Comment by matt-deboer** [comment]
same new issue as #84; try again now with latest...
