### ISSUE TITLE
Kuill Pod Crashing with 'Index Out Of Range' error

### ISSUE THREAD

**Issue by vguaglione** [matt-deboer/kuill#85]
Does this configuration work for full kubernetes or OpenShift clusters?  I ran both the kuill-dependencies and kuill-example-deployment scripts "as is" out of the box in our dev OpenShift cluster and see that the kuill pod is crashing with an 'index out of range' error.   Anyone else see this same issue?

**Comment by matt-deboer** [comment]
Sorry, it's been a little while since I've had opportunity to look at this project; I'll be revamping for current versions of kube (and openshift), react, golang, etc. over the next few months as I have time. 
What version of openshift were you testing against, btw?

**Comment by vguaglione** [comment]
No worries.  I was testing against OpenShift 3.9 (kubernetes 1.9.1).  Any ideas how I can work around this problem?  I'd like to use this dashboard in my environment so I can get installed that would be great.

**Comment by matt-deboer** [comment]
We may be able to get the current setup working...could you include a bit
more details of the crash? Maybe a stack trace from the pod logs?

**Comment by vguaglione** [comment]
This is the information we have in the pod that crashes:  

time="2018-12-03T18:48:49Z" level=warning msg="OpenID+Connect authenticator is not enabled; the following required flags were missing: oidc-provider-name, oidc-provider, oidc-client-id, oidc-client-secret, public-url"
--
  | time="2018-12-03T18:48:49Z" level=warning msg="SAML authenticator is not enabled; the following required flags were missing: saml-groups-attribute, saml-sp-cert, saml-sp-key, public-url"
  | time="2018-12-03T18:48:49Z" level=info msg="Enabled authenticator: anonymous:anonymous => /auth/anonymous/anonymous"
  | panic: runtime error: index out of range
  | goroutine 1 [running]:
  | github.com/matt-deboer/kuill/pkg/proxy.toAbbreviation(0xc4202c9380, 0x6, 0x1194666, 0x1)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/proxy/kinds.go:138 +0x114
  | github.com/matt-deboer/kuill/pkg/proxy.(*KindsProxy).update(0xc42019a0c0, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/proxy/kinds.go:103 +0x65b
  | github.com/matt-deboer/kuill/pkg/proxy.NewKindsProxy(0xc4204ae3c0, 0xc420151560, 0xc420151590, 0x0)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/proxy/kinds.go:50 +0x68
  | main.setupProxy(0xc420310c60, 0xc42005fe00, 0xc4204ae3c0)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:468 +0x1ab
  | main.main.func1(0xc420310c60)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:268 +0x293
  | github.com/matt-deboer/kuill/vendor/github.com/urfave/cli.HandleAction(0x1001d00, 0x120fa50, 0xc420310c60, 0xc42034a660, 0x0)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/vendor/github.com/urfave/cli/app.go:503 +0x7c
  | github.com/matt-deboer/kuill/vendor/github.com/urfave/cli.(*App).Run(0xc4203cf340, 0xc42000e1b0, 0x1, 0x1, 0x0, 0x0)
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/vendor/github.com/urfave/cli/app.go:268 +0x6ca
  | main.main()
  | /home/travis/gopath/src/github.com/matt-deboer/kuill/pkg/server/main.go:292 +0x25ea
